### ISSUE TITLE
DNN 7.4.2 comments and issues

### ISSUE THREAD

**Issue by jncraig** [OPSI-srl/UManage#2]
So, I have about 10 minutes experience so far.  First impression is very, very positive!

Couple of issues:
1.  When the module is "closed," the text is Italian.
2.  Clicking "Full DNN Edit" produces this error and no modal window:

TypeError: Cannot read property 'show' of undefined
    at $self.fullEdit (controller.js?cdv=39:390)
    at angular.min.js?cdv=39:198
    at f (angular.min.js?cdv=39:215)
    at l.$eval (angular.min.js?cdv=39:126)
    at l.$apply (angular.min.js?cdv=39:126)
    at HTMLAnchorElement.<anonymous> (angular.min.js?cdv=39:215)
    at HTMLAnchorElement.jQuery.event.dispatch (jquery.js?cdv=39:3074)
    at HTMLAnchorElement.elemData.handle (jquery.js?cdv=39:2750)
1.  It would be nice if the number of users per page could be adjustable.  Particularly for the tabular display.

---

Overall, great ideas, nice implementations!

**Comment by OctoD** [comment]
We will release the bugfixes very soon, thanks for reporting!

**Comment by jncraig** [comment]
Extra points for paying attention here.  Grazie!

**Comment by OctoD** [comment]
Unfortunately, we are not detecting the issues above (concerning client side). 

May you tell me if you which source/version are you using and where you downloaded (from this repo or from the dnnstore)? If you encountered these bugs, I'd love to help you and other users to get rid of them. 

The paging feature will come in with next release (with the fixes too). Thanks in advance and thanks for using our module!

**Comment by jncraig** [comment]
I downloaded PA-DNN7-UManage-00.02.04.zip from here yesterday.  I will do some more checking later today.

**Comment by OctoD** [comment]
We have updated the master branch with the updates. You will find a new filter in the aside bar. This filter will allow you to set the records per page.
